image:
  file: .gitpod.Dockerfile
tasks:
  - name: Starting Project
    before: composer create-project --prefer-dist laravel/laravel laravel "8.*"
    init: cd laravel && mysql -u root -e "create database laravel" && cp .env.example .env && sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env && sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env && composer install && npm install && php artisan key:generate
    command: php artisan migrate --seed && npm run dev &&  php artisan serve
ports:
  - port: 8000
    onOpen: open-preview
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer
