tasks:
  - name: Terminal 1
    before: echo "before script"
    init: composer create-project --prefer-dist laravel/laravel blog "5.8.*" && mv blog/{,.}* . && rm -rf blog && composer install && npm install
    command: php artisan serve && npm run watch
  - name: Terminal 2
    before: echo "before script"
    init: echo "init script"
    command: echo "command script"
ports:
  - port: 8000
    onOpen: open-preview
