tasks:
  - name: Terminal 1
    before: composer create-project --prefer-dist laravel/laravel blog "5.8.*" && mv blog/{,.}* .
    init: composer install && npm install
    command: php artisan serve
  - name: Terminal 2
    before: echo "before script"
    init: echo "init script"
    command: npm run watch
ports:
  - port: 8000
    onOpen: open-preview
